# Generated by Django 3.2.18 on 2023-06-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='article/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
