# Generated by Django 3.2.18 on 2023-06-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='heart',
            field=models.BooleanField(default=False),
        ),
    ]
